version: "3"

services:
  mongodb:
    image: mongo:3-jessie
    hostname: mongodb.infra.dev
    ports:
      - "27017:27017"
    environment:
      # Uncomment for authentication
      #
      # - MONGO_INITDB_ROOT_USERNAME=dev
      # - MONGO_INITDB_ROOT_PASSWORD=infra
      - MONGO_INITDB_DATABASE=development
    volumes:
      - ../storage/mongodb:/data/db:Z
    networks:
      - mongodb-net

  mongodb-webui:
    image: mrvautin/adminmongo:latest
    ports:
      - "27018:1234"
    networks:
      - mongodb-net
    depends_on:
      - mongodb

networks:
  mongodb-net:
