version: "3"

services:
  redis:
    image: redis:4-alpine
    hostname: redis.infra.dev
    ports:
      - "6379:6379"
    volumes:
      - ../storage/redis:/data:Z
    entrypoint: redis-server --appendonly yes
    restart: always
    networks:
      - redis-net

  redis-webui:
    image: marian/rebrow:latest
    ports:
      - "6380:5001"
    networks:
      - redis-net
    depends_on:
      - redis

networks:
  redis-net:
